// v0.15.7 historical data accumulator controls. Research only; no orders.
(function(){
const css=document.createElement('style');css.textContent=`.hist-acc{margin:10px 0;padding:11px;border:1px solid var(--line);border-radius:12px;background:rgba(18,36,58,.45)}.hist-controls{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.hist-controls select,.hist-controls button{padding:8px 10px;border-radius:10px;border:1px solid var(--line);background:#13233a;color:#dbe8f8;font-weight:700}.hist-controls button{background:#21456a}.hist-progress{height:8px;border-radius:99px;background:#0b1524;overflow:hidden;margin:9px 0}.hist-progress i{display:block;height:100%;background:#5ee0a3;width:0}.hist-meta{font-size:11px;color:var(--muted);line-height:1.55}.hist-warn{font-size:10px;color:#ffd47c;margin-top:6px}@media(max-width:520px){.hist-controls select,.hist-controls button{font-size:11px;flex:1}}`;document.head.appendChild(css);
let timer=null;
function mount(){const panel=document.querySelector('.backtest-dashboard');if(!panel){setTimeout(mount,500);return}if(document.querySelector('#histAcc'))return;const coverage=panel.querySelector('#btCoverage');const box=document.createElement('div');box.id='histAcc';box.className='hist-acc';box.innerHTML=`<div class="hist-controls"><b>과거 5분봉 자동 축적</b><select id="histDays"><option value="20">20 거래일</option><option value="60">60 거래일</option><option value="120">120 거래일</option></select><select id="histCodes"><option value="40">40 종목</option><option value="60">60 종목</option><option value="100">100 종목</option></select><button id="histStart">▶ 수집 시작</button><button id="histStop">■ 중지</button></div><div class="hist-progress"><i id="histBar"></i></div><div id="histMeta" class="hist-meta">상태 확인 중...</div><div class="hist-warn">NH 호출 제한을 지키며 순차 수집합니다. 중단 후 다시 시작해도 DB 캐시를 재사용합니다. 실전주문/전략변경 없음.</div>`;coverage.parentNode.insertBefore(box,coverage);box.querySelector('#histStart').onclick=start;box.querySelector('#histStop').onclick=stop;poll();}
async function start(){const days=document.querySelector('#histDays').value,codes=document.querySelector('#histCodes').value;try{const r=await fetch(`/api/history/start?days=${days}&max_codes=${codes}`,{method:'POST',cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'수집 시작 실패');poll(true)}catch(e){document.querySelector('#histMeta').textContent='수집 시작 실패: '+e.message}}
async function stop(){try{await fetch('/api/history/stop',{method:'POST',cache:'no-store'});poll(true)}catch(e){}}
async function poll(force=false){clearTimeout(timer);const meta=document.querySelector('#histMeta'),bar=document.querySelector('#histBar');if(!meta)return;try{const r=await fetch('/api/history/status',{cache:'no-store'}),d=await r.json(),s=d.status||{};bar.style.width=`${Number(s.progressPct||0)}%`;meta.innerHTML=`${s.running?'🟢 수집 중':'⚪ 대기'} · ${Number(s.progressPct||0).toFixed(1)}% · ${Number(s.completedJobs||0).toLocaleString()}/${Number(s.totalJobs||0).toLocaleString()} 작업 · 신규/갱신 ${Number(s.writtenBars||0).toLocaleString()}봉 · 실패 ${Number(s.failedJobs||0)}${s.currentDate?`<br>${s.currentDate} · ${s.currentCode||''}`:''}${s.lastError?`<br>최근 오류: ${String(s.lastError)}`:''}`;if(s.running)timer=setTimeout(poll,2500);else if(window.loadBacktestCoverage)window.loadBacktestCoverage();}catch(e){meta.textContent='상태 조회 실패: '+e.message;if(force)timer=setTimeout(poll,3000)}}
window.historyAccumulatorPoll=poll;mount();
})();
