// v0.16.6 Market Regime + Cross failure + Surge Discovery research UI.
(()=>{
const css=document.createElement('style');css.textContent=`.market-lab{margin:12px 0}.mr-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mr-card{padding:11px;border:1px solid var(--line);border-radius:14px;background:rgba(18,36,58,.65)}.mr-card small{display:block;color:var(--muted);font-size:10px}.mr-card strong{display:block;margin-top:3px}.mr-red{border-color:#8b4650}.mr-good{border-color:#3f9b72}.mr-table{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:5px;font-size:11px;margin-top:8px}.mr-note{font-size:11px;color:var(--muted);margin-top:9px}.mr-section{margin-top:13px;padding-top:11px;border-top:1px solid var(--line)}@media(max-width:520px){.mr-grid{grid-template-columns:1fr 1fr}.market-lab .panel-head{align-items:flex-start}body[data-mobile-tab="home"] .market-lab,body[data-mobile-tab="top"] .market-lab,body[data-mobile-tab="chart"] .market-lab{display:none}body[data-mobile-tab="learn"] .market-lab{display:block!important}}body[data-market="us"] .market-lab{display:none!important}`;document.head.appendChild(css);
const n=(v,d=2)=>Number(v||0).toFixed(d);
function mount(){const wrap=document.querySelector('.wrap');if(!wrap||document.querySelector('.market-lab'))return;const s=document.createElement('section');s.className='card panel market-lab';s.innerHTML=`<div class="panel-head"><div><h2>Market Guard & Surge Lab</h2><p>하락장 회피 · Cross 실패 역추적 · 급등 후보 사전탐색</p></div><button id="marketLabRun" class="btn">▶ 연구 실행</button></div><div id="marketLabContent" class="neutral">Control에는 반영하지 않고 Shadow 연구만 수행합니다.</div>`;const lab=document.querySelector('.strategy-lab');if(lab)lab.after(s);else wrap.appendChild(s);s.querySelector('#marketLabRun').onclick=run}
function regime(d){const g=d.groups||{};return `<div class="mr-section"><b>🌐 Market Regime Guard</b><div class="mr-grid" style="margin-top:8px">${['NORMAL','CAUTION','RED'].map(k=>{const x=g[k]||{};return `<div class="mr-card ${k==='RED'?'mr-red':k==='NORMAL'?'mr-good':''}"><small>${k}</small><strong>${x.trades||0}건 · 승률 ${n(x.winRate)}%</strong><small>PF ${n(x.profitFactor)} · 기대값 ${n(x.expectancyPct,3)}%</small></div>`}).join('')}</div><div class="mr-note">${d.warning||''}<br>RED 구간의 PF/기대값이 명확히 나쁘면 향후 신규진입 금지 게이트 후보로 승격합니다.</div></div>`}
function failure(d){const c=d.compare||{},flags=d.lossFlags||{};return `<div class="mr-section"><b>🔬 Cross Trend 2.0 통과 후 실패 분석</b><div class="mr-grid" style="margin-top:8px"><div class="mr-card"><small>분석 거래</small><strong>${d.trades||0}건</strong><small>승률 ${n(d.winRate)}%</small></div>${Object.entries(flags).slice(0,5).map(([k,v])=>`<div class="mr-card"><small>${k}</small><strong>${v}회</strong></div>`).join('')}</div><div class="mr-table"><b>지표</b><b>승리 평균</b><b>손실 평균</b>${Object.entries(c).map(([k,v])=>`<span>${k}</span><span>${v.winAvg}</span><span>${v.lossAvg}</span>`).join('')}</div><div class="mr-note">${d.note||''}</div></div>`}
function surge(d){return `<div class="mr-section"><b>🚀 Early Surge Discovery</b><div class="mr-grid" style="margin-top:8px"><div class="mr-card"><small>실제 급등</small><strong>${d.actualSurges||0}</strong></div><div class="mr-card"><small>사전 후보</small><strong>${d.candidates||0}</strong></div><div class="mr-card mr-good"><small>적중</small><strong>${d.hits||0}</strong></div><div class="mr-card"><small>정밀도</small><strong>${n(d.precisionPct)}%</strong></div><div class="mr-card"><small>재현율</small><strong>${n(d.recallPct)}%</strong></div><div class="mr-card"><small>오탐</small><strong>${d.falsePositives||0}</strong></div></div><div class="mr-note">급등 정의: ${d.definition}. ${d.scoreRule}<br>목표는 급등 후 추격매수가 아니라 <b>09:00~09:30 특징으로 09:30 이후 후보군을 미리 좁히는 것</b>입니다.</div></div>`}
async function run(){const b=document.querySelector('#marketLabRun'),box=document.querySelector('#marketLabContent');if(!b||!box)return;b.disabled=true;b.textContent='분석 중...';try{const r=await fetch('/api/research/market-lab?max_codes=40',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'연구 오류');box.innerHTML=failure(d.failureAnalysis||{})+regime(d.marketRegime||{})+surge(d.surgeDiscovery||{})+`<div class="mr-note"><b>${d.recommendation}</b><br>Control v0.8.0 LOCKED · 자동변경 OFF · REAL ORDER OFF</div>`}catch(e){box.innerHTML=`<span class="lab-bad">실패: ${e.message}</span>`}finally{b.disabled=false;b.textContent='▶ 연구 실행'}}
function init(){mount();setTimeout(mount,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,350));else setTimeout(init,350);
})();
