// v0.16.3 Cross Trend / Overnight Lab UI. Research only.
(()=>{
const css=document.createElement('style');css.textContent=`.strategy-lab{margin:12px 0}.lab-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.lab-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.lab-card{border:1px solid var(--line);border-radius:14px;padding:11px;background:rgba(18,36,58,.65)}.lab-card.control{border-color:#456b8d}.lab-card.best{border-color:#4acb91;box-shadow:0 0 0 1px rgba(74,203,145,.15) inset}.lab-card small{display:block;color:var(--muted);font-size:10px}.lab-card b{display:block;margin:3px 0 8px}.lab-m{display:grid;grid-template-columns:1fr 1fr;gap:5px;font-size:11px}.lab-m span{color:var(--muted)}.lab-note{margin-top:9px;font-size:11px;color:var(--muted)}.lab-best{color:#62dfa2;font-weight:800}.lab-bad{color:#ff7d88}.overnight-box{margin-top:14px;padding-top:12px;border-top:1px solid var(--line)}.overnight-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.overnight-actions select{background:#14263b;color:inherit;border:1px solid var(--line);border-radius:10px;padding:9px}.strategy-lab .btn{white-space:nowrap}@media(max-width:520px){.lab-grid{grid-template-columns:1fr 1fr}.lab-card.control{grid-column:1/-1}body[data-mobile-tab="home"] .strategy-lab,body[data-mobile-tab="top"] .strategy-lab,body[data-mobile-tab="chart"] .strategy-lab{display:none}body[data-mobile-tab="learn"] .strategy-lab{display:block}}body[data-market="us"] .strategy-lab{display:none!important}`;document.head.appendChild(css);
function mount(){if(document.querySelector('.strategy-lab'))return;const wrap=document.querySelector('.wrap');if(!wrap)return;const s=document.createElement('section');s.className='card panel strategy-lab';s.innerHTML=`<div class="lab-head"><div><h2>Cross Trend Lab</h2><p>Control v0.8.0 LOCKED · EMA/MA 추세전환 + Overnight 연구</p></div><button id="labRun" class="btn">▶ 전략 비교</button></div><div id="labContent" class="neutral" style="margin-top:10px">Cross Trend와 ORB+Cross를 기존 Challenger와 동일 데이터에서 비교합니다.</div><div class="overnight-box"><div class="overnight-actions"><select id="trendKind"><option value="cross_trend">Cross Trend</option><option value="orb_cross">ORB + Cross Trend</option><option value="orb_rvol">ORB + RVOL</option></select><button id="overnightRun" class="btn">▶ Overnight 비교</button></div><div id="overnightContent" class="lab-note">당일청산 vs 1박/2박/3박/최대 5거래일을 비교합니다. 추세 훼손 시 조기청산합니다.</div></div>`;const bt=document.querySelector('.backtest-dashboard');if(bt)bt.after(s);else wrap.appendChild(s);s.querySelector('#labRun').onclick=run;s.querySelector('#overnightRun').onclick=overnight}
function n(v,d=2){const x=Number(v||0);return Number.isFinite(x)?x.toFixed(d):'-'}
function cards(items,best){return `<div class="lab-grid">${items.map(x=>{const isbest=x.id===best,control=x.role==='CONTROL',ex=Number(x.expectancyPct||0);return `<div class="lab-card ${control?'control':''} ${isbest?'best':''}"><small>${control?'CONTROL':'CHALLENGER'}${isbest?' · BEST':''}</small><b>${x.name}</b><div class="lab-m"><span>거래</span><strong>${x.trades||0}</strong><span>승률</span><strong>${n(x.winRate)}%</strong><span>PF</span><strong>${Number(x.profitFactor)===999?'∞':n(x.profitFactor)}</strong><span>기대값</span><strong class="${ex>=0?'lab-best':'lab-bad'}">${ex>=0?'+':''}${n(ex,3)}%</strong><span>MDD</span><strong>${n(x.maxDrawdownPct)}%</strong></div></div>`}).join('')}</div>`}
async function run(){const b=document.querySelector('#labRun'),box=document.querySelector('#labContent');b.disabled=true;b.textContent='비교 중...';try{const r=await fetch('/api/strategy-lab/run?max_codes=40',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Lab 오류');box.innerHTML=cards(d.strategies||[],d.bestChallenger)+`<div class="lab-note">${d.warning}<br>Control 자동교체 OFF · 실전주문 OFF</div>`}catch(e){box.innerHTML=`<span class="lab-bad">실패: ${e.message}</span>`}finally{b.disabled=false;b.textContent='▶ 전략 비교'}}
async function overnight(){const b=document.querySelector('#overnightRun'),box=document.querySelector('#overnightContent'),kind=document.querySelector('#trendKind').value;b.disabled=true;b.textContent='검증 중...';try{const r=await fetch('/api/strategy-lab/exit?strategy='+encodeURIComponent(kind),{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Overnight Lab 오류');box.innerHTML=cards((d.results||[]).map(x=>({...x,role:'CHALLENGER'})),d.bestExit)+`<div class="lab-note">게이트: <b>${d.gate}</b> · ${d.passGate?'<span class="lab-best">1차 통과</span>':'아직 미통과'}<br>${d.overnightRisk}<br>${d.warning}</div>`}catch(e){box.innerHTML=`<span class="lab-bad">실패: ${e.message}</span>`}finally{b.disabled=false;b.textContent='▶ Overnight 비교'}}
function init(){mount();const nav=document.querySelector('.mobile-nav');if(nav){const learn=nav.querySelector('[data-tab="learn"]');if(learn)learn.addEventListener('click',()=>setTimeout(mount,50))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();
