// v0.16.1 Strategy Lab UI - research only, Control v0.8.0 remains locked.
(()=>{
const css=document.createElement('style');css.textContent=`.strategy-lab{margin:12px 0}.lab-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.lab-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px}.lab-card{border:1px solid var(--line);border-radius:14px;padding:11px;background:rgba(18,36,58,.65)}.lab-card.control{border-color:#456b8d}.lab-card.best{border-color:#4acb91;box-shadow:0 0 0 1px rgba(74,203,145,.15) inset}.lab-card small{display:block;color:var(--muted);font-size:10px}.lab-card b{display:block;margin:3px 0 8px}.lab-m{display:grid;grid-template-columns:1fr 1fr;gap:5px;font-size:11px}.lab-m span{color:var(--muted)}.lab-note{margin-top:9px;font-size:11px;color:var(--muted)}.lab-best{color:#62dfa2;font-weight:800}.lab-bad{color:#ff7d88}.strategy-lab .btn{white-space:nowrap}@media(max-width:520px){.lab-grid{grid-template-columns:1fr 1fr}.lab-card.control{grid-column:1/-1}body[data-mobile-tab="home"] .strategy-lab,body[data-mobile-tab="top"] .strategy-lab,body[data-mobile-tab="chart"] .strategy-lab{display:none}body[data-mobile-tab="learn"] .strategy-lab{display:block}}body[data-market="us"] .strategy-lab{display:none!important}`;document.head.appendChild(css);
function mount(){if(document.querySelector('.strategy-lab'))return;const wrap=document.querySelector('.wrap');if(!wrap)return;const s=document.createElement('section');s.className='card panel strategy-lab';s.innerHTML=`<div class="lab-head"><div><h2>Strategy Lab</h2><p>Control v0.8.0 LOCKED vs 유명 데이트레이딩 계열 Challenger</p></div><button id="labRun" class="btn">▶ 전략 비교</button></div><div id="labContent" class="neutral" style="margin-top:10px">같은 5분봉에서 ORB·VWAP Pullback·Momentum·First Pullback을 비교합니다.</div>`;const bt=document.querySelector('.backtest-dashboard');if(bt)bt.after(s);else wrap.appendChild(s);s.querySelector('#labRun').onclick=run}
function n(v,d=2){const x=Number(v||0);return Number.isFinite(x)?x.toFixed(d):'-'}
async function run(){const b=document.querySelector('#labRun'),box=document.querySelector('#labContent');if(!b||!box)return;b.disabled=true;b.textContent='비교 중...';box.textContent='Control과 4개 Challenger를 동일 데이터에서 재생 중입니다...';try{const r=await fetch('/api/strategy-lab/run?max_codes=40',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||'Strategy Lab 오류');box.innerHTML=`<div class="lab-grid">${(d.strategies||[]).map(x=>{const best=x.id===d.bestChallenger,control=x.role==='CONTROL',ex=Number(x.expectancyPct||0);return `<div class="lab-card ${control?'control':''} ${best?'best':''}"><small>${control?'CONTROL':'CHALLENGER'}${best?' · BEST':''}</small><b>${x.name}</b><div class="lab-m"><span>거래</span><strong>${x.trades||0}</strong><span>승률</span><strong>${n(x.winRate)}%</strong><span>PF</span><strong>${Number(x.profitFactor)===999?'∞':n(x.profitFactor)}</strong><span>기대값</span><strong class="${ex>=0?'lab-best':'lab-bad'}">${ex>=0?'+':''}${n(ex,3)}%</strong></div></div>`}).join('')}</div><div class="lab-note">${d.warning||''}<br>Control 자동교체: <b>OFF</b> · 실전주문: <b>OFF</b> · 테스트 ${d.codesTested||0}종목</div>`}catch(e){box.innerHTML=`<span class="lab-bad">Strategy Lab 실패: ${e.message}</span>`}finally{b.disabled=false;b.textContent='▶ 전략 비교'}}
function init(){mount();const nav=document.querySelector('.mobile-nav');if(nav){const learn=nav.querySelector('[data-tab="learn"]');if(learn)learn.addEventListener('click',()=>setTimeout(mount,50))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();
