// v0.17.3 hotfix: Strategy/Overnight buttons read cached automatic research; no heavy manual reruns.
(()=>{
const css=document.createElement('style');css.textContent=`.strategy-lab{margin:12px 0}.lab-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.lab-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.lab-card{border:1px solid var(--line);border-radius:14px;padding:11px;background:rgba(18,36,58,.65)}.lab-card.control{border-color:#456b8d}.lab-card.best{border-color:#4acb91;box-shadow:0 0 0 1px rgba(74,203,145,.15) inset}.lab-card small{display:block;color:var(--muted);font-size:10px}.lab-card b{display:block;margin:3px 0 8px}.lab-m{display:grid;grid-template-columns:1fr 1fr;gap:5px;font-size:11px}.lab-m span{color:var(--muted)}.lab-note{margin-top:9px;font-size:11px;color:var(--muted)}.lab-best{color:#62dfa2;font-weight:800}.lab-bad{color:#ff7d88}.filter-box{margin-top:10px;padding:10px;border:1px dashed #48627d;border-radius:12px}.filter-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px;font-size:10px}.overnight-box{display:block!important;margin-top:16px;padding:14px;border:1px solid #35516f;border-radius:14px;background:rgba(14,31,50,.72)}.overnight-box h3{margin:0 0 5px;font-size:16px}.overnight-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.overnight-actions select{flex:1;min-width:160px;background:#14263b;color:inherit;border:1px solid var(--line);border-radius:10px;padding:10px}@media(max-width:520px){.lab-grid{grid-template-columns:1fr 1fr}.lab-card.control{grid-column:1/-1}.overnight-actions{display:grid;grid-template-columns:1fr}.overnight-actions select,.overnight-actions .btn{width:100%}body[data-mobile-tab="home"] .strategy-lab,body[data-mobile-tab="top"] .strategy-lab,body[data-mobile-tab="chart"] .strategy-lab{display:none}body[data-mobile-tab="learn"] .strategy-lab{display:block!important}}body[data-market="us"] .strategy-lab{display:none!important}`;document.head.appendChild(css);
function overnightMarkup(){return `<div class="overnight-box" data-overnight-lab="1"><h3>🌙 Cross Trend 2.0 Overnight Lab</h3><div class="lab-note">자동 연구가 계산해 둔 보유기간 비교 결과를 즉시 보여줍니다. 실전 주문에는 반영하지 않습니다.</div><div class="overnight-actions"><select id="trendKind"><option value="cross_trend_v2">Cross Trend 2.0 + False Filter</option><option value="cross_trend">Cross Trend 1.0</option><option value="orb_cross">ORB + Cross Trend</option><option value="orb_rvol">ORB + RVOL</option></select><button id="overnightRun" class="btn">▶ 최신 결과 보기</button></div><div id="overnightContent" class="lab-note">당일청산 vs 1박 / 2박 / 3박 / 최대 5거래일 자동 연구 결과를 불러옵니다.</div></div>`}
function bindOvernight(s){const b=s.querySelector('#overnightRun');if(b&&!b.dataset.bound){b.dataset.bound='1';b.onclick=overnight}}
function mount(){const wrap=document.querySelector('.wrap');if(!wrap)return;let s=document.querySelector('.strategy-lab');if(s){if(!s.querySelector('[data-overnight-lab]'))s.insertAdjacentHTML('beforeend',overnightMarkup());else{const old=s.querySelector('[data-overnight-lab]');if(old)old.outerHTML=overnightMarkup()}bindOvernight(s);const rb=s.querySelector('#labRun');if(rb){rb.textContent='▶ 최신 결과 보기';rb.onclick=run}return}s=document.createElement('section');s.className='card panel strategy-lab';s.innerHTML=`<div class="lab-head"><div><h2>Cross Trend 2.0 Lab</h2><p>Control v0.8.0 LOCKED · 자동 연구 결과 조회</p></div><button id="labRun" class="btn">▶ 최신 결과 보기</button></div><div id="labContent" class="neutral" style="margin-top:10px">자동 연구에서 계산된 최신 전략 비교 결과를 불러옵니다.</div>${overnightMarkup()}`;const bt=document.querySelector('.backtest-dashboard');if(bt)bt.after(s);else wrap.appendChild(s);s.querySelector('#labRun').onclick=run;bindOvernight(s)}
function n(v,d=2){const x=Number(v||0);return Number.isFinite(x)?x.toFixed(d):'-'}
function cards(items,best){return `<div class="lab-grid">${items.map(x=>{const isbest=x.id===best,control=x.role==='CONTROL',ex=Number(x.expectancyPct||0);return `<div class="lab-card ${control?'control':''} ${isbest?'best':''}"><small>${control?'CONTROL':'CHALLENGER'}${isbest?' · BEST':''}</small><b>${x.name}</b><div class="lab-m"><span>거래</span><strong>${x.trades||0}</strong><span>승률</span><strong>${n(x.winRate)}%</strong><span>PF</span><strong>${Number(x.profitFactor)===999?'∞':n(x.profitFactor)}</strong><span>기대값</span><strong class="${ex>=0?'lab-best':'lab-bad'}">${ex>=0?'+':''}${n(ex,3)}%</strong><span>MDD</span><strong>${n(x.maxDrawdownPct)}%</strong></div></div>`}).join('')}</div>`}
function diagnostics(items){const x=(items||[]).find(v=>v.id==='cross_trend_v2');if(!x||!x.falseSignalFilter)return'';const d=x.falseSignalFilter,names={accepted:'통과',no_fresh_cross:'신선한 Cross 아님',whipsaw:'Whipsaw 반복',no_compression:'사전 압축 부족',weak_slope:'기울기 약함',regime_or_vwap:'장기추세/VWAP 불량',weak_trend:'ADX·DMI 약함',low_volume:'거래량 부족',overextended:'과열/추격',rsi_filter:'RSI 범위 밖',failed_persistence:'Cross 지속 실패'};return `<div class="filter-box"><b>🛡️ False Signal Filter</b><div class="filter-grid">${Object.entries(d).map(([k,v])=>`<span>${names[k]||k}</span><strong>${v}</strong>`).join('')}</div><div class="lab-note">거래수를 줄이는 대신 PF·기대값·MDD가 개선되는지 평가합니다.</div></div>`}
async function latest(){const r=await fetch('/api/research/final',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||`HTTP ${r.status}`);return d}
async function run(){const b=document.querySelector('#labRun'),box=document.querySelector('#labContent');if(!b||!box)return;b.disabled=true;b.textContent='불러오는 중...';try{const root=await latest(),d=root.strategy;if(!d||!Array.isArray(d.strategies)||!d.strategies.length)throw new Error('자동 전략 연구 결과가 아직 준비되지 않았습니다.');box.innerHTML=cards(d.strategies||[],d.bestChallenger)+diagnostics(d.strategies)+`<div class="lab-note">${d.warning||''}<br>자동 연구 시각: ${root.generatedAt||'-'}<br>Control 자동교체 OFF · 실전주문 OFF</div>`}catch(e){box.innerHTML=`<span class="lab-bad">실패: ${e.message}</span><div class="lab-note">새 계산을 시작하지 않고 서버가 저장한 자동 연구 결과만 조회합니다.</div>`}finally{b.disabled=false;b.textContent='▶ 최신 결과 보기'}}
async function overnight(){const b=document.querySelector('#overnightRun'),box=document.querySelector('#overnightContent'),sel=document.querySelector('#trendKind');if(!b||!box||!sel)return;const kind=sel.value;b.disabled=true;b.textContent='불러오는 중...';try{const root=await latest(),d=root.overnight?.[kind];if(!d||!Array.isArray(d.results)||!d.results.length)throw new Error('Overnight 자동 연구 결과가 아직 준비되지 않았습니다. 서버 자동 연구 완료 후 다시 확인해 주세요.');box.innerHTML=cards((d.results||[]).map(x=>({...x,role:'CHALLENGER'})),d.bestExit)+`<div class="lab-note">게이트: <b>${d.gate}</b> · ${d.passGate?'<span class="lab-best">1차 통과</span>':'아직 미통과'}<br>${d.overnightRisk}<br>${d.warning}<br>자동 연구 시각: ${root.generatedAt||'-'}</div>`}catch(e){box.innerHTML=`<span class="lab-bad">${e.message}</span><div class="lab-note">버튼을 눌러 새 백테스트를 돌리지 않습니다. 자동 연구가 완료된 결과만 즉시 표시합니다.</div>`}finally{b.disabled=false;b.textContent='▶ 최신 결과 보기'}}
function init(){mount();const nav=document.querySelector('.mobile-nav');if(nav){const learn=nav.querySelector('[data-tab="learn"]');if(learn)learn.addEventListener('click',()=>setTimeout(mount,50))}setTimeout(mount,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();
