// v0.13.1 mobile app shell. Presentation only; trading logic untouched.
const style=document.createElement('style');style.textContent=`
.mobile-nav{display:none}
@media(max-width:520px){body{padding-bottom:70px}.mobile-nav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;left:0;right:0;bottom:0;z-index:100;background:rgba(9,16,29,.98);border-top:1px solid var(--line);padding:6px 6px calc(6px + env(safe-area-inset-bottom));backdrop-filter:blur(12px)}.mobile-nav button{border:0;background:transparent;color:var(--muted);font-weight:800;font-size:10px;min-height:48px;border-radius:10px}.mobile-nav button.active{background:#12243a;color:#7db4ff}.mobile-nav b{display:block;font-size:17px;margin-bottom:2px}
body[data-mobile-tab="home"] .metrics{display:grid;grid-template-columns:1fr 1fr}body[data-mobile-tab="home"] .metrics .metric:nth-child(2),body[data-mobile-tab="home"] .metrics .metric:nth-child(3),body[data-mobile-tab="home"] .metrics .metric:nth-child(4),body[data-mobile-tab="home"] .metrics .metric:nth-child(6){display:none}body[data-mobile-tab="home"] .metrics:after{content:'시스템 정상\A SAFE FILTER ON · REAL ORDER OFF';white-space:pre-line;display:flex;flex-direction:column;justify-content:center;padding:13px;border:1px solid var(--line);border-radius:16px;background:var(--card);font-weight:800;color:#62dfa2;font-size:12px}body[data-mobile-tab="home"] .connection-panel{display:block}body[data-mobile-tab="home"] .connect-row{display:none}body[data-mobile-tab="home"] .connection-panel .panel-head p{display:none}body[data-mobile-tab="home"] .main-grid{display:flex}body[data-mobile-tab="home"] .main-grid>article,body[data-mobile-tab="home"] .main-grid>aside{display:block}body[data-mobile-tab="home"] .chart-grid,body[data-mobile-tab="home"] .lower-grid,body[data-mobile-tab="home"] .wrap>section.card.panel:last-of-type{display:none}body[data-mobile-tab="home"] .main-grid article .table-wrap{max-height:260px;overflow:hidden}body[data-mobile-tab="home"] .main-grid article tr.pick-row:nth-of-type(n+4){display:none!important}body[data-mobile-tab="home"] .main-grid article .panel-head h2{font-size:0}body[data-mobile-tab="home"] .main-grid article .panel-head h2:after{content:'현재 BUY 후보 TOP 3';font-size:14px}body[data-mobile-tab="home"] .main-grid article .panel-head p{display:none}
body[data-mobile-tab="top"] .metrics,body[data-mobile-tab="top"] .connection-panel,body[data-mobile-tab="top"] .main-grid>aside,body[data-mobile-tab="top"] .chart-grid,body[data-mobile-tab="top"] .lower-grid,body[data-mobile-tab="top"] .wrap>section.card.panel:last-of-type{display:none}body[data-mobile-tab="top"] .main-grid{display:block;margin-top:0}
body[data-mobile-tab="chart"] .metrics,body[data-mobile-tab="chart"] .connection-panel,body[data-mobile-tab="chart"] .main-grid,body[data-mobile-tab="chart"] .lower-grid,body[data-mobile-tab="chart"] .wrap>section.card.panel:last-of-type{display:none}body[data-mobile-tab="chart"] .chart-grid{display:grid;margin-top:0}
body[data-mobile-tab="learn"] .metrics,body[data-mobile-tab="learn"] .connection-panel,body[data-mobile-tab="learn"] .main-grid,body[data-mobile-tab="learn"] .chart-grid{display:none}body[data-mobile-tab="learn"] .lower-grid{display:grid}body[data-mobile-tab="learn"] .wrap>section.card.panel:last-of-type{display:block}
#scanBtn.scan-action{min-width:88px;border-radius:12px;padding:8px 11px;background:#5ee0a3;color:#052117;font-size:11px}#remoteUpdateBtn.secondary-action{border-radius:12px;padding:8px 10px;background:#16243a;color:#dbe8f8;border:1px solid #33445f;font-size:11px}#nhCheckBtn.utility-action{border-radius:12px;background:#163a30;color:#8cf0c0;border:1px solid #245e4b}
}`;document.head.appendChild(style);
function makeNav(){if(!matchMedia('(max-width:520px)').matches||document.querySelector('.mobile-nav'))return;const nav=document.createElement('nav');nav.className='mobile-nav';nav.innerHTML=`<button data-tab="home"><b>⌂</b>대시보드</button><button data-tab="top"><b>☷</b>TOP10</button><button data-tab="chart"><b>⌁</b>차트·매매</button><button data-tab="learn"><b>▣</b>학습·로그</button>`;document.body.appendChild(nav);const setTab=t=>{document.body.dataset.mobileTab=t;localStorage.setItem('daytrader-mobile-tab',t);nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));scrollTo({top:0,behavior:'instant'})};nav.querySelectorAll('button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));setTab(localStorage.getItem('daytrader-mobile-tab')||'home');window.dayTraderMobileTab=setTab;document.addEventListener('click',e=>{const row=e.target.closest?.('.pick-row');if(row)setTimeout(()=>setTab('chart'),30)},true)}makeNav();
